import 'angular-material';
import 'jquery.appear';
import 'magnific-popup';
import 'nanoscroller';
import 'whatwg-fetch';
import 'zone.js';
import * as $ from 'jquery';
import * as DOMPurify from 'dompurify';
import * as Konami from 'konami-code.js';
import * as MarkdownIt from 'markdown-it';
import * as SimpleWebRTC from 'simplewebrtc';
import * as WOW from 'wowjs';
import * as angular from 'angular';
import * as braintree from 'braintree-web';
import * as clipboard from 'clipboard-js';
import * as firebase from 'firebase';
import * as markdownItEmoji from 'markdown-it-emoji';
import * as markdownItSup from 'markdown-it-sup';
import * as tabIndent from 'tab-indent';
import {BrowserModule, Title} from '@angular/platform-browser';
import {ChangeDetectorRef, Component, ElementRef, Input, OnInit} from '@angular/core';
import {ChangeDetectorRef} from '@angular/core';
import {CommonModule} from '@angular/common';
import {Component, ElementRef, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {Component, ElementRef, Input, OnChanges, Renderer, SimpleChanges} from '@angular/core';
import {Component, ElementRef, Input, OnInit} from '@angular/core';
import {Component, ElementRef, Input} from '@angular/core';
import {Component, Input, OnInit} from '@angular/core';
import {Component, Input} from '@angular/core';
import {Component, OnInit} from '@angular/core';
import {Component} from '@angular/core';
import {Directive, ElementRef, OnDestroy, OnInit} from '@angular/core';
import {Directive, ElementRef, Renderer} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {Injectable} from '@angular/core';
import {NativeScriptModule} from 'nativescript-angular/platform';
import {NgModule, NO_ERRORS_SCHEMA} from '@angular/core';
import {NgModule} from '@angular/core';
import {Subject} from 'rxjs/Subject';
import {Title} from '@angular/platform-browser';
import {UpgradeComponent} from '@angular/upgrade/static';
import {UpgradeModule} from '@angular/upgrade/static';
import {downgradeComponent, UpgradeModule} from '@angular/upgrade/static';
import {enableProdMode} from '@angular/core';
import {mceliece} from 'mceliece';
import {microlight} from 'microlight-string';
import {ntru} from 'ntru';
import {platformBrowser} from '@angular/platform-browser';
import {platformNativeScript} from 'nativescript-angular/platform-static';
import {rlwe} from 'rlwe';
import {saveAs} from 'file-saver';
import {sodiumUtil} from 'sodiumutil';
import {superSphincs} from 'supersphincs';


console.log('balls');
